//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPlenario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Telefonos
    {
        public int TelefonoID { get; set; }
        public int PersonaID { get; set; }
        [StringLength(20, ErrorMessage = "El {0} debe tener mínimo {2} números y máximo {1} números",MinimumLength =6)]
        public string Telefono { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
